language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'

notifications:
  email: false

sudo: false
