language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-android-support

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'

sudo: false
